README.md

I guess the previous version used the `rollNavigation` in the `AutoCompleteList` component, but now it must be included in `AutoComplete`

docs: fix examples using rollNavigation

---

README.md
example/src/App.tsx

Updated `README` and `/example` to fix the AutoCompleteTag label not showing
Closes #55

chore(docs): fix AutoCompleteTag label

---

src/autocomplete-group.tsx

Mentioned in comments for #67 
baseStyle props were applied after the props - making any matching styles set by the baseStyles override the props.

Fixed issue with styles in AutoCompleteGroupTitle not being overridden

---

src/helpers/items.ts
src/types.ts

Added a new property `originalValue` to `Item` in order to expose the original value that was passed in. Fixes #117 and is a follow-up enhancement to #60.  This is important since it allows you to now be able to access the other values inside the original value from the `onSelectOption` callback.
Example of item with `originalValue` property.

Exposes original value object to onSelectOption

---

README.md
src/autocomplete-item.tsx
src/use-autocomplete.ts

As it stands, `fixed` is filtered out of the suggestions if these two conditions are met:
- there exists a maxSuggestions limit
- the `fixed` item index > maxSuggestions
My proposal is to keep that functionality but add another prop `alwaysShow` that behaves similar to `fixed` except it shows in suggestions regardless of maxSuggestions limit.

Modify 'fixed' prop to show item regardless of both filter and maxSuggestions.

---

src/use-autocomplete.ts

`focusedItem` can be `undefined` (the type is `any`) and this make the component crashing.
Since the if statement was just to `console.log("last")` I just removed it…

Fix: App crashing on `Tab` press

---

example/src/App.tsx
package.json
src/autocomplete-creatable.tsx
src/autocomplete-input.tsx
src/types.ts
src/use-autocomplete.ts
tsconfig.json
vite.config.js
yarn.lock

As someone using yarn 3 wich is quite strict with packages dependencies having all dependencies declared, and setting the external is a huge benefit. 
Also migrated the build to vite to have faster build. TSDX is still used just for the lint / test part. 
Also fix the peerDep that was set to chakra v1

feat: 🎸 rework dependencies

---

README.md
src/autocomplete-input.tsx

This adds a `hidePlaceholder` prop to the `AutoCompleteInput` component. 
It allows the placeholder to be hidden when the children array is not empty. This is useful in the following example:
```ts
// example/src/App.tsx
import { Flex, FormControl, FormLabel } from "@chakra-ui/react";
import * as React from "react";
import {
AutoComplete,
AutoCompleteInput, AutoCompleteTag
} from "../../src/index";
function App() {
return (
<Flex pt="48" justify="center" align="center" w="full">
<FormControl>
<FormLabel htmlFor="select-role">Default</FormLabel>
<AutoComplete multiple creatable onChange={vals => console.log(vals)}>
<AutoCompleteInput
placeholder="Enter email addresses.."
variant="outline"
hidePlaceholder
>
{({ tags }) =>
tags.map((tag, tid) => (
<AutoCompleteTag
key={tid}
label={tag.label} …
```

feat: :guitar: add hidePlaceholder prop

---

package.json
yarn.lock

Fix for when using creatable, rest of the list is not shown.
[Issue](https://github.com/anubra266/choc-autocomplete/issues/148) [Issue 2.](https://github.com/anubra266/choc-autocomplete/issues/159)
(https://github.com/anubra266/choc-autocomplete/issues/148) Seems like the issues was because react-nany didn't handle children correctly.

fix: creatable list

---

package.json
yarn.lock

Hi,
when we try to install the library with npm this problem comes up:
<br/>
<br/>
This problem was also encountered by other users since I saw that there is an [open issue here](https://github.com/anubra266/choc-autocomplete/issues/175).
Thought I'd update the "framer-motion" dependency since as of today it's up to version 10.12.10.
At the moment I have no idea how I can test this edit on my real production project, do you have any ideas?
I tried to install the local repository (forked repo) in my project (my production project) but it gave me an error.
@anubra266 do you have any ideas how I can test it?
Thanks

fix: framer motion

---

README.md

In the README, the `submitKeys` prop of the AutoComplete component is incorrectly described.
Before my change the `submitKeys` prop had the same description as the `suggestWhenEmpty` prop. I changed the description from: 
*show suggestions when input value is empty*
to
*A list of KeyboardEvent: key values, except for the "Enter" key, that trigger the click event of the currently selected Item.*
I also changed the default value of the prop to &mdash;&mdash;&mdash;

Fixed description and default value of the AutoComplete submitKeys prop in docs

---

src/helpers/items.ts
src/use-autocomplete.ts

Suggested fix for #172 will normalize values to a string
If your values prop and defaultValues prop contain numbers instead of strings, the wrong label is displayed on the tags and the selected items aren't highlighted correctly in the list
Proposed fix is to treat number values as strings which keeps in line with default behavior of manually selecting an item from the dropdown (newly added item will be a string) as well as what would happen if this was a regular <select> element instead.

Fix #172 defaultValue with Array of Number

---

src/use-autocomplete.ts

Fix for issue #152 to add back in support for escape and tab characters
Thought process:   Escape should just close the list without any further action.
**Tab functionality**
When pressing tab, it should function like a select where the currently selected item becomes the value, the select closes, and the focusable item is focused. If no value is selected, the select will simply close and focus the next item.
Replaced call to setFocusedValue with selectItem.  If no value currently selected, simply call onClose
**Escape functionality**
The escape issue appeared to be an issue with the callAll utility.  It would return a function that you can run, but I was unable to figure out how to run the function.  Replaced with calling each function individually.
**Arrow up/down**
Also fixes an issue …

Fix #152 support for escape and tab

---

src/use-autocomplete.ts

Fix #140 
Fix #150 
Fix #156 
This should fix above issues which all seemed to suffer from the same underlying issue: if `AutoComplete` is rendered as a child of something the pre-renders content as `hidden` like `Tabs`, `Accordion`, `Collapse`, etc the width returned by `useDimensions` incorrectly states 0px.
Reading the docs, it looks like `useDimensions` was deprecated and replaced with `useSize` instead.  This new hook doesn't appear to have the same issue if the item is rendered within a parent container that is hidden.
I tested all 3 scenarios locally and this appears to work correctly.  When combined with PR #189 the content is even rendered correctly within the popover and will no longer be hidden by things like `AccordionPanel`

Fix #140 #150 #156 - List not displayed when parent is pre-rendered

---

src/helpers/input.ts

Fixes #190 where several invalid attribute errors would pop up when using the `multiple` attribute.
Applying this attempts to convert all of the --input* attributes that are created and then applied to the `Wrap` component.  The equivalent to these ie --input-padding: space.4 should be converted into just padding: 4.  This seems to work correctly for all of the existing errors that were happening.  I have not tested this exhaustively with every single prop that could be passed to the `Input` component and then subsequently passed on to the `Wrap` component.
This also fixes #177 which reported the same issue specifically with `_focus`

Fix #190 input to wrap style conversion

---

src/autocomplete-input.tsx
src/autocomplete-list.tsx

After adding the loading props and merging some other PRs, some invalid props began being sent to the `Input` and `PopoverContent` components.  This fixes those errors by explicitly destructuring `props`

fix: invalid props

---

README.md
src/use-autocomplete.ts

When multiple=true, should default to false.  When multiple=false, should default to true
Fix #145

Fix closeOnSelect default

---

src/autocomplete-list.tsx
src/autocomplete.tsx
src/types.ts
src/use-autocomplete.ts

Reduces render of AutoComplete component by 2 for each action:
initial render, open, close, select, etc
Initial render performance increase
AutoComplete = 3 => 1
AutoCompleteList = 3 => 1
AutoCompleteInput = 3 => 2
Accomplished by removing need for getListProps which depends on useSize
Per below issue, the matchWidth prop correctly calculates width
width=inherit needs to be passed to PopoverContent
https://github.com/chakra-ui/chakra-ui/issues/4104

perf: reduce AutoComplete renders

---

src/autocomplete-input.tsx

Fix #217 filtered items don't reset after form submit/reset
When using a controlled input, the filtered list that appears when you open the list does not reset itself.  Solution was to watch the value prop being passed in so that when you reset the form values, the filtered results will also be reset.

fix: filtered items not resetting on form submit

---

README.md
src/types.ts
src/use-autocomplete.ts

Most of the time, this component tends to prefocuses first suggestion. This is done in a way that in not configurable and slightly inconsistent. For example, if you want to match behavior of Google Autocomplete on this aspect, you can't (GAC doesn't prefocus first item).
- It prefocuses first item in most cases
- On initially render
- On query change
- On open
- NOT on filter out of currently focused item
- When prefocusFirstItem is true (default)
- On initially render
- On query change
- On open
- On on filter out of currently focused item
- When false
- Do not prefocus on all events above

Make prefocusFirstItem behavior configurable and consistent

---

src/autocomplete-input.tsx
src/types.ts
src/use-autocomplete.ts

According to the documentation, the `value` prop is supposed to make the component act like a controlled input.  It doesn't appear to do anything.
In order for a truly controlled component, you had to pass `value` to both `AutoComplete` and `AutoCompleteInput`.  While this worked, it caused a lot of confusion with how the component worked.  It also had the unintended consequence of making `AutoCompleteInput` always display the current value rather than the label of the item that was passed in.
Passing `value` to `AutoComplete` will now make this a controlled input as described by the documentation.  If the `value` is changed outside of component, the `AutoCompleteInput` will correctly update with the label associated with the new `value`
Fixes #235

Fix `value` prop does nothing

---

README.md
demo/package.json
demo/src/app.jsx
demo/src/formik.jsx
demo/src/react-hook-form.jsx
demo/yarn.lock

Form libraries can sometimes be a challenge.  This will document the basic needs for 2 of the most popular libraries out there right now: react-hook-form and formik.  This is not an exhaustive list of integrations with libraries, but should help users get up and running quickly and easily.

Doc: Add form library integration documentation

---

src/use-autocomplete.ts

`removeItem` did not behave as expected.  There were 2 separate issues.
* If the value passed in did not match the label being displayed, it did not function correctly
* `onChange` was being called before the value of the `query` being displayed in the input changed, so it wouldn't be possible to remove what was selected
Fixes #247

Fix issues with removeItem

---

package.json
vite.config.js

Update build process to use export default and type module.  This fixes an issue where under some setups you would receive a named export error
Fixes #241

Fix: named export error due to build issue

---

README.md
src/autocomplete.tsx
src/types.ts

Adds a new property called `matchWidth` which is passed directly to the Chakra UI Popover `matchWidth` prop.  Defaults to true
#252

252ExposeMaxWidth

---

src/autocomplete-item.tsx

This PR fixes a bug that causes the window to constantly scroll when navigating with the keyboard. This was caused by the following useEffect:
if (isFocused && interactionRef.current === "keyboard")
itemRef?.current?.scrollIntoView({
behavior: "smooth",
block: "center",
});
}, [isFocused, interactionRef]);
I assume the intention here was to make the selected element visible when you pressed the keyboard. But because the block variable is set to "center", the browser will try to move the item to the center of the window every time the keyboard is pressed.
Changing this to block: "nearest" changes the behaviour so it only scrolls the screen if the selected element isn't visible. 
Fixes #253

Changed scrollIntoView behaviour to fix scrolling issue when navigating with keyboard

---

package.json
src/use-autocomplete.ts

The focus of the first item should be reseted also when the list changes:
`
useUpdateEffect(() => {
if (prefocusFirstItem)
setFocusedValue(firstItem?.value);
}, [query, firstItem]);
`
This happens specially when the source data comes from an API and the list constantly changes.
Fixes: #257

fix: reset the focus of the first item when the list changes

---

src/use-autocomplete.ts

Sometimes the `firstItem` is the same but it goes inside the effect causing a reset on the focused value even when neither the list nor the query has changed.
Pass only `firstItem?.value` to the dependencies array.

fix set focused value when first item changes

---

src/use-autocomplete.ts

I encored a bug, when the `emptyState` is `false` and there is no suggestion and the suggestion box was already open, it will show an empty suggestion box.
```tsx
<AutoComplete emptyState={false}>
...
```
This small fix closes the suggestion box, in that case

fix: close state when `emptyState` is false and there is no suggestions

---

vite.config.js

Currently, the bundle produced by `yarn build` includes the production and development versions of the react jsx runtime.
This PR adds the (internal) `react/jsx-runtime` package to the `rollupOptions` external field, which excludes it from bundling.
Bundling the jsx runtime is not a problem as long as the importing application is using the same version of react as `choc-autocomplete`, i.e. 18, but when importing from an application using react 19, it will error out.
Additionally, this cuts the bundle size in ~half.
```
❯ yarn build
yarn run v1.22.22
$ vite build
vite v5.4.11 building for production...
✓ 41 modules transformed.
[vite:dts] Start generate declaration files...
dist/index.js  29.58 kB │ gzip: 11.39 kB
[vite:dts] Declaration files built in 2018ms.
dist/index.es.js  44.43 kB │ …
```

Don't bundle react/jsx-runtime (fixes React 19)

---

package.json

#285 
Relax React `peerDependency` from `^18.2.0` to `>=18.2.0` to support React 19, while still remaining compatible with React 18.
This solves the following `ERESOLVE` error when using `@choc-ui/chakra-autocomplete@"^6.0.0"` as sa dependency from a  React 19 project:

chore: Updated peerDependency for react 19 compatibility

---

src/use-autocomplete.ts

When the `multiple` mode is enabled, and there is something in the input to filter the list, the `Enter` key press does not trigger the `onChange` with the focused item.
Since the new values are pushed to the end of the values array, it would be correct to check the last element instead of the first one in the `onChange` callback of the `values` state in the `useAutoComplete` hook.
P.S. It would be nice to have it backported to v5 as well.

fix: select the correct item on `Enter` keypress in the multiple mode

---

src/autocomplete-input.tsx

The issue was caused by the `Input` being wrapped by an `InputGroup` when the loading state needed to be shown and not being wrapped by an `InputGroup` when the loading state did not need to be shown.
This would cause the `Input` to lose focus causing a bad UX.  We will now always render an `InputGroup` and pass the `endElement` prop based on the `isLoading` prop.
For consideration:
If you have a custom icon being displayed, the loading state will still display correctly but it looks weird because you will have 2 icons on top of each other.  Because of this, I am considering removing the `isLoading` and `loadingState` props in v7.  These should probably be external concerns that the users control themselves.
For what it's worth, the Chakra UI `Combobox` component functions this way where …

fix: #297 input loses focus when changing isLoading
