anubra266/choc-autocomplete

- example/app.tsx
- src/helpers/autocomplete-props/onSelectOption.ts
> 🐛 fix(onSelectOption) isNewInput always false

- example/app.tsx
- package.json
- src/helpers/input.ts
- src/helpers/list.ts
- src/store/reducers/item.ts
- yarn.lock
> filter with Items' text

- src/helpers/items.ts
> 🐛 Special characters crashing regex

- README.md
- example/src/App.tsx
- src/autocomplete-item.tsx
- src/autocomplete.tsx
- src/types.ts
- src/use-autocomplete.ts
> ✨ Add `listAllValuesOnFocus` prop.

- .all-contributorsrc
- README.md
Reverts anubra266/choc-autocomplete#59
> Revert "docs: add eric-hc as a contributor for code"

- README.md
- demo/package.json
- demo/public/index.html
- demo/src/app.js
- demo/src/basic.js
- demo/src/creatable.js
- demo/src/custom-render.js
- demo/src/group.js
- demo/src/index.js
- demo/src/multi-select.js
- demo/src/with-icon.js
Resolves #56 
Moved codesandbox demo into the project, updated package.json to use latest choc-autocomplete version and updated readme to open the `githubbox` link from the demo folder.
> Moved codesandbox demo into project

- example/src/App.tsx
- src/autocomplete-input.tsx
- src/use-autocomplete.ts
> Fix Input trapping tab focus

- README.md
@anubra266 not sure if you want to include this, but figured I'd throw this up just in case. Feel free to close or add it yourself if you'd prefer to do it another way.
> Updating `AutoCompleteInput` docs to include ref prop

- README.md
Updating docs to include restoreOnBlur prop from #68 
Thanks for the amazingly fast turnaround time, @anubra266!!!!!
> Adding docs for new restoreOnBlur prop

- README.md
- example/src/App.tsx
- src/autocomplete-creatable.tsx
Fixes #129 
Adds the `alwaysDisplay` prop to `AutoCompleteCreatable`
> Add `alwaysDisplay` prop

- example/src/App.tsx
- src/autocomplete-creatable.tsx
- src/helpers/list.ts
> Fix: TypeError: null is not an object (evaluating 'child.type')

- src/autocomplete-input.tsx
> Fixing an issue with the isInvalid prop

- README.md
- renamed "restoreOnBlur" to "restoreOnBlurIfEmpty"
> docs(README): use updated prop name

- demo/package.json
- demo/src/index.js
- example/package.json
- example/src/main.tsx
- example/yarn.lock
- package.json
- src/autocomplete-creatable.tsx
- src/autocomplete-input.tsx
- src/use-autocomplete.ts
- yarn.lock
update the autocomplete component to use chakra ui V2 under the hood
BREAKING CHANGE: 🧨 Now using chakra-ui@2.x and react@18.x
> feat: 🎸 update to chakra-v2

- example/src/ex2.tsx
- package.json
- yarn.lock
Missing two dependencies that i forgot to add in the last PR, just a small patch. 
```
"@chakra-ui/layout": "latest"
"@chakra-ui/tag": "latest"
```
> fix: 🐛 missing dependencies

- package-lock.json
- package.json
- yarn.lock
**(Don't merge at the moment)**
----------
Sorry for the mistake, this is the same PR of this [old PR](https://github.com/anubra266/choc-autocomplete/pull/178).
Now the installation of the library seems to work, but before merging I would like to understand how best to test the library on another project so as to have a fair test before merging.
----------
This is the old data for the issue.
when we try to install the library with npm this problem comes up:
<br/>
<br/>
This problem was also encountered by other users since I saw that there is an [open issue here](https://github.com/anubra266/choc-autocomplete/issues/175).
Thought I'd update the "framer-motion" dependency since as of today it's up to version 10.12.10.
At the moment I have no idea how I can test this edit on my real …
> wip: framer motion

- package-lock.json
- package.json
- tsconfig.json
- vite.config.js
Update to latest version of vite and reconfigure build process
This also fixes #167 which would display incorrect colors when in dark mode
> chore: update to latest version of vite

- package.json
> Add types export in package.json

- package-lock.json
- package.json
> Moved react-nanny to dependencies

- package.json
- yarn.lock
There was a bug in size-limit on Windows
Upgrading to version 11 corrected the issue
> fix: size-limit error

- src/use-autocomplete.ts
> fix: tab when closed selects last focused element

- package.json
- src/autocomplete-context.ts
- src/autocomplete-creatable.tsx
- src/autocomplete-group.tsx
- src/autocomplete-input.tsx
- src/autocomplete-item.tsx
- src/autocomplete-tag.tsx
- src/autocomplete.tsx
- src/helpers/group.ts
- src/helpers/items.ts
- src/types.ts
- src/use-autocomplete.ts
- src/utils.ts
In relation to #267.
Suggesting we remove the dependency on utils package as it has been deprecated by chakra ui.
> Remove utils dependency
